[package]
name = "nix-snow"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "snow"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = "4.0"
nix-data = { git = "https://github.com/snowflakelinux/nix-data", branch = "main" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
owo-colors = { version = "3.5", features = ["supports-colors"] }
lazy_static = "1.4"
ijson = "0.1"
nix-editor = "0.3.0-beta.1"
pretty_env_logger = "0.4"
